Rewrite in shell script

diff --git a/scripts/git-ignore b/scripts/git-ignore
--- a/scripts/git-ignore
+++ b/scripts/git-ignore
@@ -1,33 +1,24 @@
-#!/usr/bin/env python3
-from __future__ import annotations
+#!/usr/bin/env bash
 
-import argparse
-import sys
-
-import requests
-
-
-def main(argv=None) -> int:
-    parser = argparse.ArgumentParser()
-    parser.add_argument('lang')
-    args = parser.parse_args(argv)
-
-    lang = args.lang.capitalize()
-    url = f'https://raw.githubusercontent.com/github/gitignore/main/{lang}.gitignore'
-
-    try:
-        response = requests.get(url)
-        response.raise_for_status()
-
-        with open('.gitignore', 'a') as f:
-            f.write(response.text)
-        print(f'.gitignore for {lang} downloaded successfully.')
-
-        return 0
-    except Exception:
-        print(f'Error: A .gitignore was not found for {lang}', file=sys.stderr)
+main() {
+    if [ $# -ne 1 ]; then
+        echo "Usage: $0 <lang>"
         return 1
+    fi
 
+    lang=$(echo "$1" | awk '{print toupper(substr($0, 1, 1)) tolower(substr($0, 2))}')
+    url="https://raw.githubusercontent.com/github/gitignore/main/${lang}.gitignore"
 
-if __name__ == '__main__':
-    raise SystemExit(main())
+    response=$(curl -sS "$url")
+
+    if [ $? -ne 0 ]; then
+        echo "Error: .gitignore was not found for $lang" >&2
+        return 1
+    fi
+
+    echo "$response" >> .gitignore
+    echo ".gitignore for $lang added."
+    return 0
+}
+
+main "$@"
